#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if [[ $publishing == '1' ]]; then
  # do nothing during publishing because npm test has run in the `preversion` phase
  echo ''
else
  npm test
fi
